[project]
name = "course-llamaindex"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "litellm",
    "python-dotenv",
    "llama-index-core",
    "llama-index-llms-litellm",
    "llama-index-embeddings-huggingface",
    "llama-index-vector-stores-chroma",
    "chromadb",
    "sentence-transformers",
]
